### ISSUE TITLE
Ansible handler can't get ntp_service variable from vars/RedHat.yml and vars/Debian.yml

### ISSUE THREAD

**Issue by TS0TNE** [perfsonar/ansible-role-perfsonar-testpoint#23]
The notify part does not work in these peace of code:  

```yml
# NTP is essential for good measurements
- name: Configure additional NTP servers
  tags: [ 'ps::config' ]
  blockinfile:
    path: /etc/ntp.conf
    block: |
      server {{ item.hostname }} iburst
    marker: "# {mark} ansible-role-perfsonar {{ item.name }}"
  with_items: "{{ perfsonar_ntp_servers }}"
  notify:
    - restart ntp
```
because in vars/RedHat.yml (vars/Debian.yml) we have variable definition like this:  

```yml
perfsonar_testpoint_os_specific_services:
  - httpd
  - postgresql-10
  - "{{ ntp_service | default('ntpd') }}"
```

and "ntp_service" variable can't be determined in handlers/main.yml correctly:

```yml
- name: restart ntp
  service:
    name: "{{ ntp_service }}"
    state: restarted
```
